# Assignment 3
## By Alejandro Vera

### why when you slice and store any value(s) using NumPy and store it in a new variable it changes the value in the original variable

When you slice a value in NumPy and store it in a different variable the value is not coppied into a different array it is refrenced in the new variable so if you make a change in the new variable then that modifications are also make in the source array.

## Ndarrays

In [25]:
import numpy as np

# create nested sequences with 5 values in each
nested_seq = [[1, 2, 3, 4, 5],[6, 7, 8, 9 ,10],[11, 12, 13, 14, 15],[16, 17, 18, 19 ,20],[21, 22, 23, 24, 25]]

# conert that object into an np array 
nd_arr = np.array(nested_seq);

print(nd_arr.shape)

(5, 5)


In [26]:
# use the np.zeros function to create a 3 by 6 array
zero_arr = np.zeros((6,3))

print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# use aragne to start at 1.5 and go to 20 with it incrementing by 3 each time
Q3 = np.arange(1.5, 20, 3)

print(Q3)

[ 1.5  4.5  7.5 10.5 13.5 16.5 19.5]


In [28]:
# use the astype function to conver the floats into ints, removing the deximals and their numbers
Q4 = Q3.astype(np.int)

print(Q4)

[ 1  4  7 10 13 16 19]


## Slicing

In [29]:
#create new numpy range
pepper = np.arange(5, 200, 5)

print(pepper)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195]


In [30]:
# slice the array and take the 6th, 7th, and 8th value into this new array
arrSlice = pepper[5:8]

print(arrSlice)

arrSlice[0] = 1  
arrSlice[1] = 2
arrSlice[2] = 3

print(arrSlice)

[30 35 40]
[1 2 3]


In [31]:
# select items 6 - 8 in original array
pepper[5:8]

array([1, 2, 3])

In [32]:
# create 3 by 3 grid with random numbers 
grid = np.random.uniform(size=(3,3))
print(grid)

# select second row first column item
print(grid[1][0])

[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]
0.5513147690828912


## Randomize Example

In [33]:
# set numpy random seed 
np.random.seed(123)

In [34]:
# set random state
rng = np.random.RandomState(12345)

In [35]:
# generate random values and stpre in to variable
sortrng = rng.randn(10);

print(sortrng)

# sort values in sortrng
sortrng.sort()

print(sortrng)

[-0.20470766  0.47894334 -0.51943872 -0.5557303   1.96578057  1.39340583
  0.09290788  0.28174615  0.76902257  1.24643474]
[-0.5557303  -0.51943872 -0.20470766  0.09290788  0.28174615  0.47894334
  0.76902257  1.24643474  1.39340583  1.96578057]


## Indexing

In [36]:
# create an array with the given values
prod = np.array(['McClane', 'Hans', 'Harry', 'Holly'])

print(prod)

['McClane' 'Hans' 'Harry' 'Holly']


In [37]:
# boolean indexing to see if 'Hans' is in the list
prod == 'Hans'


array([False,  True, False, False])

In [38]:
# create new list with given values
income = np.array([[192722, 178381, 123411, 118498],
       [129418, 169760, 104442, 196768],
       [111788, 107343, 154896, 118256],
       [119197, 107314, 100670, 148633]]
)

print(income)

[[192722 178381 123411 118498]
 [129418 169760 104442 196768]
 [111788 107343 154896 118256]
 [119197 107314 100670 148633]]


In [39]:
# get the max income for Hans row
income[prod == 'Hans'].max()

196768

In [40]:
# find the sum of arrays using the columns
income.sum(axis=0)

array([553125, 562798, 483419, 582155])

In [41]:
# find the sum of the rows
income.sum(axis=1)

array([613012, 600388, 492283, 475814])

In [42]:
# std using numpy functions
std = income.std(axis=1)

print('Standard Deviation: ', std)

# var
var = income.var(axis=1)

print('Variance: ', var)

# min
min = income.min(axis=1)

print('Min: ', min)

# max
max = income.max(axis=1)

print('Max: ', max)


Standard Deviation:  [32740.16391987 35625.8890275  18779.58281452 18375.91048765]
Variance:  [1.07191833e+09 1.26920397e+09 3.52672731e+08 3.37674086e+08]
Min:  [118498 104442 107343 100670]
Max:  [192722 196768 154896 148633]
